id: D127FA118
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:45:14+00:00'
last_modified: '2022-05-27T06:08:44.110059+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4cfd:
      image_group_id: I1PD95902
      title: ཡེ་ཤེས་སྙིང་པོ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1605
      order: 57
      base_file: 4cfd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
