id: P9DA92979
initial_creation_type: ocr
source_metadata:
  volumes:
    09b66814ad8d4b468d29e6b98a4cb0b5:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཡེ་ཤེས་སྙིང་པོ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1605
      volume_number: 57
